# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50)),
                ('api_name', models.CharField(max_length=50)),
                ('population', models.IntegerField(default=0)),
            ],
        ),
    ]
